
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."

  Run-PSScriptAnalyzer-on-Windows:
    name: Run PSScriptAnalyzer on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
      - name: Get list of rules
        shell: pwsh
        run: |
          Get-ScriptAnalyzerRule

      - name: My first step
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
        run: echo This event is a pull request that had an assignee removed. No this will be the pull-request.


  job_1:
    name: Add 7 and 11
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 7 + 11 > math-work.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: work_pre
          path: math-work.txt

  job_2: 
    name: Divide by 2
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: work_pre
      - shell: bash
        run: |
          value=`cat math-work.txt`
          expr $value \/ 2 > math-work.txt
      - name: Uplod math result for the job 2
        uses: actions/upload-artifact@v4
        with:
          name: work_final
          path: math-work.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download the last math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: work_final
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-work.txt`
          echo The result is $value
